// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/molotovtv/tc/tc/build.proto

package tc

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	io "io"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Build struct {
	ID                   int         `protobuf:"varint,1,opt,name=ID,proto3,casttype=int" json:"id"`
	Status               BuildStatus `protobuf:"bytes,2,opt,name=Status,proto3,casttype=BuildStatus" json:"status"`
	BranchName           string      `protobuf:"bytes,3,opt,name=BranchName,proto3" json:"branchName"`
	State                BuildState  `protobuf:"bytes,4,opt,name=State,proto3,casttype=BuildState" json:"state"`
	PercentageComplete   float32     `protobuf:"fixed32,5,opt,name=PercentageComplete,proto3" json:"percentageComplete"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4bb525bd519b201, []int{0}
}
func (m *Build) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Build.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return m.Size()
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetID() int {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Build) GetStatus() BuildStatus {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Build) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *Build) GetState() BuildState {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Build) GetPercentageComplete() float32 {
	if m != nil {
		return m.PercentageComplete
	}
	return 0
}

func init() {
	proto.RegisterType((*Build)(nil), "tc.Build")
}

func init() {
	proto.RegisterFile("github.com/molotovtv/tc/tc/build.proto", fileDescriptor_f4bb525bd519b201)
}

var fileDescriptor_f4bb525bd519b201 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x6a, 0x84, 0x30,
	0x10, 0x87, 0x49, 0xac, 0x42, 0xa7, 0x7f, 0x0e, 0x39, 0xb4, 0xb6, 0x50, 0x23, 0x3d, 0x14, 0x2f,
	0xab, 0x94, 0xbe, 0x41, 0xba, 0x14, 0xf6, 0x52, 0x8a, 0x7d, 0x02, 0x75, 0x53, 0x57, 0x50, 0x23,
	0xee, 0xb8, 0xe7, 0x3e, 0x5e, 0x8f, 0x7d, 0x82, 0x50, 0x3c, 0xfa, 0x08, 0x9e, 0x8a, 0xb1, 0x2c,
	0x0b, 0x5d, 0xc8, 0x21, 0x33, 0xf3, 0x7d, 0xf3, 0x83, 0x81, 0x87, 0xbc, 0xc0, 0x4d, 0x97, 0x86,
	0x99, 0xaa, 0xa2, 0x4a, 0x95, 0x0a, 0xd5, 0x0e, 0x77, 0x11, 0x66, 0xd3, 0x4b, 0xbb, 0xa2, 0x5c,
	0x87, 0x4d, 0xab, 0x50, 0x31, 0x8a, 0xd9, 0xed, 0xe2, 0x80, 0xcd, 0x55, 0xae, 0x22, 0x33, 0x4a,
	0xbb, 0x0f, 0x53, 0x99, 0xc2, 0xfc, 0x66, 0xe5, 0xfe, 0x93, 0x82, 0x2d, 0xa6, 0x15, 0xec, 0x0e,
	0xe8, 0x6a, 0xe9, 0x12, 0x9f, 0x04, 0x96, 0xb8, 0x18, 0x34, 0xa7, 0xc5, 0x7a, 0xd4, 0xdc, 0x2a,
	0x6a, 0x8c, 0xe9, 0x6a, 0xc9, 0x1e, 0xc1, 0x79, 0xc7, 0x04, 0xbb, 0xad, 0x4b, 0x7d, 0x12, 0x9c,
	0x8a, 0x9b, 0x41, 0x73, 0x67, 0x6b, 0x3a, 0xa3, 0xe6, 0x67, 0x66, 0xc7, 0x0c, 0xc4, 0x7f, 0x20,
	0x0b, 0x01, 0x44, 0x9b, 0xd4, 0xd9, 0xe6, 0x35, 0xa9, 0xa4, 0x6b, 0x19, 0xed, 0x72, 0xd0, 0x1c,
	0xd2, 0x7d, 0x37, 0x3e, 0x20, 0xd8, 0x02, 0xec, 0xc9, 0x94, 0xee, 0x89, 0x41, 0xaf, 0x07, 0xcd,
	0xed, 0x29, 0x41, 0x8e, 0x9a, 0xc3, 0x3e, 0x40, 0xc6, 0x33, 0xc5, 0x5e, 0x80, 0xbd, 0xc9, 0x36,
	0x93, 0x35, 0x26, 0xb9, 0x7c, 0x56, 0x55, 0x53, 0x4a, 0x94, 0xae, 0xed, 0x93, 0x80, 0x8a, 0xab,
	0x41, 0x73, 0xd6, 0xfc, 0x9b, 0xc6, 0x47, 0x0c, 0x71, 0xfe, 0xd5, 0x7b, 0xe4, 0xbb, 0xf7, 0xc8,
	0x4f, 0xef, 0x91, 0xd4, 0x31, 0x77, 0x79, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x31, 0xfc,
	0x92, 0x74, 0x01, 0x00, 0x00,
}

func (m *Build) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Build) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBuild(dAtA, i, uint64(m.ID))
	}
	if len(m.Status) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBuild(dAtA, i, uint64(len(m.Status)))
		i += copy(dAtA[i:], m.Status)
	}
	if len(m.BranchName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintBuild(dAtA, i, uint64(len(m.BranchName)))
		i += copy(dAtA[i:], m.BranchName)
	}
	if len(m.State) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintBuild(dAtA, i, uint64(len(m.State)))
		i += copy(dAtA[i:], m.State)
	}
	if m.PercentageComplete != 0 {
		dAtA[i] = 0x2d
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.PercentageComplete))))
		i += 4
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintBuild(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Build) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovBuild(uint64(m.ID))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovBuild(uint64(l))
	}
	l = len(m.BranchName)
	if l > 0 {
		n += 1 + l + sovBuild(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovBuild(uint64(l))
	}
	if m.PercentageComplete != 0 {
		n += 5
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovBuild(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozBuild(x uint64) (n int) {
	return sovBuild(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Build) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBuild
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Build: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Build: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuild
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuild
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = BuildStatus(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BranchName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuild
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuild
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BranchName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuild
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuild
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = BuildState(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field PercentageComplete", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.PercentageComplete = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipBuild(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBuild
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBuild
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBuild(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBuild
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBuild
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthBuild
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowBuild
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipBuild(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthBuild
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthBuild = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBuild   = fmt.Errorf("proto: integer overflow")
)
