// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/aestek/tc/tc/build.proto

/*
	Package tc is a generated protocol buffer package.

	It is generated from these files:
		github.com/aestek/tc/tc/build.proto

	It has these top-level messages:
		Build
*/
package tc

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Build struct {
	ID                 int         `protobuf:"varint,1,opt,name=ID,proto3,casttype=int" json:"id"`
	Status             BuildStatus `protobuf:"bytes,2,opt,name=Status,proto3,casttype=BuildStatus" json:"status"`
	BranchName         string      `protobuf:"bytes,3,opt,name=BranchName,proto3" json:"branchName"`
	State              BuildState  `protobuf:"bytes,4,opt,name=State,proto3,casttype=BuildState" json:"state"`
	PercentageComplete float32     `protobuf:"fixed32,5,opt,name=PercentageComplete,proto3" json:"percentageComplete"`
}

func (m *Build) Reset()                    { *m = Build{} }
func (m *Build) String() string            { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()               {}
func (*Build) Descriptor() ([]byte, []int) { return fileDescriptorBuild, []int{0} }

func (m *Build) GetID() int {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Build) GetStatus() BuildStatus {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Build) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *Build) GetState() BuildState {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Build) GetPercentageComplete() float32 {
	if m != nil {
		return m.PercentageComplete
	}
	return 0
}

func init() {
	proto.RegisterType((*Build)(nil), "tc.Build")
}
func (m *Build) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Build) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBuild(dAtA, i, uint64(m.ID))
	}
	if len(m.Status) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBuild(dAtA, i, uint64(len(m.Status)))
		i += copy(dAtA[i:], m.Status)
	}
	if len(m.BranchName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintBuild(dAtA, i, uint64(len(m.BranchName)))
		i += copy(dAtA[i:], m.BranchName)
	}
	if len(m.State) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintBuild(dAtA, i, uint64(len(m.State)))
		i += copy(dAtA[i:], m.State)
	}
	if m.PercentageComplete != 0 {
		dAtA[i] = 0x2d
		i++
		i = encodeFixed32Build(dAtA, i, uint32(math.Float32bits(float32(m.PercentageComplete))))
	}
	return i, nil
}

func encodeFixed64Build(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Build(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintBuild(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Build) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovBuild(uint64(m.ID))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovBuild(uint64(l))
	}
	l = len(m.BranchName)
	if l > 0 {
		n += 1 + l + sovBuild(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovBuild(uint64(l))
	}
	if m.PercentageComplete != 0 {
		n += 5
	}
	return n
}

func sovBuild(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozBuild(x uint64) (n int) {
	return sovBuild(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Build) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBuild
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Build: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Build: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuild
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = BuildStatus(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BranchName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuild
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BranchName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuild
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = BuildState(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field PercentageComplete", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.PercentageComplete = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipBuild(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBuild
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBuild(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBuild
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBuild
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthBuild
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowBuild
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipBuild(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthBuild = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBuild   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("github.com/aestek/tc/tc/build.proto", fileDescriptorBuild) }

var fileDescriptorBuild = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0x87, 0x49, 0xd6, 0x16, 0x8c, 0x7f, 0x0e, 0x39, 0x68, 0x15, 0x6c, 0x8a, 0x5e, 0x7a, 0xd9,
	0x16, 0xf1, 0x0d, 0xe2, 0x22, 0xec, 0x45, 0xa4, 0x3e, 0x41, 0xdb, 0x1d, 0xbb, 0xc5, 0x6d, 0x53,
	0xda, 0xe9, 0xdd, 0xc7, 0xf3, 0xe8, 0x13, 0x04, 0xe9, 0x31, 0x8f, 0xd0, 0x93, 0x34, 0x95, 0x65,
	0x41, 0x21, 0x87, 0xcc, 0xcc, 0xf7, 0xcd, 0x0f, 0x86, 0xdd, 0x15, 0x25, 0x6e, 0xfb, 0x2c, 0xca,
	0x55, 0x15, 0xa7, 0xd0, 0x21, 0xbc, 0xc7, 0x98, 0x4f, 0x2f, 0xeb, 0xcb, 0xdd, 0x26, 0x6a, 0x5a,
	0x85, 0x8a, 0x53, 0xcc, 0xaf, 0x97, 0x07, 0x60, 0xa1, 0x0a, 0x15, 0xdb, 0x51, 0xd6, 0xbf, 0xd9,
	0xca, 0x16, 0xf6, 0x37, 0x2b, 0xb7, 0x1f, 0x94, 0x39, 0x72, 0x5a, 0xc1, 0x6f, 0x18, 0x5d, 0xaf,
	0x3c, 0x12, 0x90, 0x70, 0x21, 0xcf, 0x8c, 0x16, 0xb4, 0xdc, 0x8c, 0x5a, 0x2c, 0xca, 0x1a, 0x13,
	0xba, 0x5e, 0xf1, 0x7b, 0xe6, 0xbe, 0x62, 0x8a, 0x7d, 0xe7, 0xd1, 0x80, 0x84, 0xc7, 0xf2, 0xca,
	0x68, 0xe1, 0x76, 0xb6, 0x33, 0x6a, 0x71, 0x62, 0x77, 0xcc, 0x40, 0xf2, 0x0b, 0xf2, 0x88, 0x31,
	0xd9, 0xa6, 0x75, 0xbe, 0x7d, 0x4e, 0x2b, 0xf0, 0x16, 0x56, 0x3b, 0x37, 0x5a, 0xb0, 0x6c, 0xdf,
	0x4d, 0x0e, 0x08, 0xbe, 0x64, 0xce, 0x64, 0x82, 0x77, 0x64, 0xd1, 0x4b, 0xa3, 0x85, 0x33, 0x25,
	0xc0, 0xa8, 0x05, 0xdb, 0x07, 0x40, 0x32, 0x53, 0xfc, 0x89, 0xf1, 0x17, 0x68, 0x73, 0xa8, 0x31,
	0x2d, 0xe0, 0x51, 0x55, 0xcd, 0x0e, 0x10, 0x3c, 0x27, 0x20, 0x21, 0x95, 0x17, 0x46, 0x0b, 0xde,
	0xfc, 0x99, 0x26, 0xff, 0x18, 0xf2, 0xf4, 0x73, 0xf0, 0xc9, 0xd7, 0xe0, 0x93, 0xef, 0xc1, 0x27,
	0x99, 0x6b, 0xef, 0xf2, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0x87, 0x5f, 0x8f, 0xfc, 0x71, 0x01,
	0x00, 0x00,
}
